# 全局块 (Main)
# user  nobody;             # 指定工作进程的用户和组,为了安全通常设为 nginx 或 www-data，避免使用 root
worker_processes  auto;    # Nginx 进程数，一般设置为和 CPU 核数一样,auto会自动匹配CPU核心数

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;
#pid        logs/nginx.pid;  # Nginx 服务启动时的 pid 存放位置

# 事件块 (Events)
events {
    worker_connections  1024; # 每个进程允许最大并发数
    # use epoll;              # 指定事件模型,Linux下推荐使用epoll
    multi_accept on;          # 允许工作进程一次性接受所有新连接，在高并发下能提升效率。
}

# 可嵌套多个server，配置代理，缓存，日志定义等绝大多数功能和第三方模块的配置
http {
    include       mime.types;
    default_type  application/octet-stream;    # 默认文件类型
    # 定义访问日志的输出格式，log_format 在 http 配置块中进行定义，这样会对所有的 server 块生效。
    # Nginx 中常用的日志格式有 main、combined
    log_format  custom  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status [$request_length:$body_bytes_sent] [$request_time:$upstream_response_time] "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
    # 文件传输优化
    sendfile        on;     # 启用高效文件传输（零拷贝），避免用户态和内核态切换
    tcp_nopush      on;     # 配合sendfile，在数据包达到最大段时才发送，提升网络效率
    tcp_nodelay     on;     # 禁用Nagle算法，保持实时性（通常与keepalive配合）

    # 缓存与缓冲区
    client_body_buffer_size 128k;   # 客户端请求体缓冲区，过大浪费内存，过小会写入磁盘
    client_max_body_size 100m;      # 限制上传文件大小（根据业务调整）
    proxy_buffering on;             # 开启代理缓冲，后端响应慢时先缓存再发给客户端
    proxy_buffer_size 4k;           # 代理响应头缓冲区

    # 超时设置
    client_header_timeout 10s;      # 读取客户端请求头超时
    client_body_timeout 10s;        # 读取请求体超时
    keepalive_timeout 65s;          # 长连接保持时间，不宜过短，也不宜过长（如超过75s）
    proxy_connect_timeout 5s;       # 连接后端超时
    proxy_read_timeout 60s;         # 从后端读取响应超时

    server_tokens off;              # 隐藏响应头中的版本号,防止攻击者针对特定版本漏洞扫描

    gzip  on;

    # 限流配置，限制每个IP每秒钟只能发起10个请求，
    limit_req_zone $binary_remote_addr zone=auth:10m rate=10r/s;

    # 服务器块 (Server) - 虚拟主机 
    server {
        listen       80;       # 监听的端口和IP地址
        server_name  localhost;# 域名匹配规则。支持精确匹配、通配符（*.example.com）和正则表达式。
        # access_log  logs/host.access.log  main;

        # 位置块 (Location) - URL路由
        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }

    # 默认：表示引入 /etc/nginx/conf.d/ 目录下所有以 .conf 结尾的文件作为 Nginx 的配置文件
    # 单独的 server 块可以放在 conf.d 目录下，方便管理和维护不同的虚拟主机配置
    include /Users/qinmao/Desktop/project/Front-End-Study/nginx/server.conf/*.conf; 
}
